package pfu3_francesccoll;

import java.util.concurrent.Semaphore;

public class Crono extends javax.swing.JFrame {

    public Crono() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butt_Start = new javax.swing.JButton();
        butt_Stop = new javax.swing.JButton();
        butt_Restart = new javax.swing.JButton();
        textField_Hores = new javax.swing.JTextField();
        textField_Minuts = new javax.swing.JTextField();
        textField_Segons = new javax.swing.JTextField();
        progersB_Hores = new javax.swing.JProgressBar();
        progersB_Minuts = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        butt_Start.setBackground(new java.awt.Color(51, 51, 51));
        butt_Start.setForeground(new java.awt.Color(153, 255, 255));
        butt_Start.setText("Start");
        butt_Start.setPreferredSize(new java.awt.Dimension(82, 32));
        butt_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_StartActionPerformed(evt);
            }
        });

        butt_Stop.setBackground(new java.awt.Color(51, 51, 51));
        butt_Stop.setForeground(new java.awt.Color(153, 255, 255));
        butt_Stop.setText("Stop");
        butt_Stop.setPreferredSize(new java.awt.Dimension(82, 32));
        butt_Stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_StopActionPerformed(evt);
            }
        });

        butt_Restart.setBackground(new java.awt.Color(51, 51, 51));
        butt_Restart.setForeground(new java.awt.Color(153, 255, 255));
        butt_Restart.setText("Restart");
        butt_Restart.setPreferredSize(new java.awt.Dimension(82, 32));
        butt_Restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_RestartActionPerformed(evt);
            }
        });

        textField_Hores.setEditable(false);
        textField_Hores.setBackground(new java.awt.Color(102, 102, 102));
        textField_Hores.setForeground(new java.awt.Color(0, 0, 153));
        textField_Hores.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_Hores.setText("0");
        textField_Hores.setToolTipText("");
        textField_Hores.setPreferredSize(new java.awt.Dimension(84, 22));

        textField_Minuts.setEditable(false);
        textField_Minuts.setBackground(new java.awt.Color(102, 102, 102));
        textField_Minuts.setForeground(new java.awt.Color(51, 153, 255));
        textField_Minuts.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_Minuts.setText("0");
        textField_Minuts.setPreferredSize(new java.awt.Dimension(84, 22));
        textField_Minuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_MinutsActionPerformed(evt);
            }
        });

        textField_Segons.setEditable(false);
        textField_Segons.setBackground(new java.awt.Color(102, 102, 102));
        textField_Segons.setForeground(new java.awt.Color(153, 255, 255));
        textField_Segons.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_Segons.setText("0");
        textField_Segons.setMinimumSize(new java.awt.Dimension(84, 22));
        textField_Segons.setPreferredSize(new java.awt.Dimension(84, 22));

        progersB_Minuts.setMaximum(60);

        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Hores");

        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Minuts");

        jLabel3.setForeground(new java.awt.Color(153, 255, 255));
        jLabel3.setText("Segons");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(progersB_Hores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(butt_Stop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(textField_Hores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField_Minuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textField_Segons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(progersB_Minuts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butt_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butt_Restart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(butt_Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt_Stop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_Segons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_Minuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField_Hores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(butt_Restart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progersB_Hores, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(progersB_Minuts, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    boolean iniciat = false, stop = false;
    public static int hores, minuts, segons;
    Thread sec;
    private void butt_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_StartActionPerformed
        if(iniciat == false){
            iniciat = true;
            Semaphore s = new Semaphore(1);
            sec = new Thread(new Timer(s, s));
            sec.start();
            textField_Segons.setText(Integer.toString(segons));
        } else if (stop == true){
            sec.resume();
            stop = false;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_StartActionPerformed

    private void textField_MinutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_MinutsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_MinutsActionPerformed

    private void butt_StopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_StopActionPerformed
        sec.suspend();
        stop = true;
    }//GEN-LAST:event_butt_StopActionPerformed

    private void butt_RestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_RestartActionPerformed
       iniciat = false;
       textField_Segons.setText("0");
       textField_Minuts.setText("0");
       textField_Hores.setText("0");
       sec.suspend();
       
       progersB_Minuts.setValue(0);
       progersB_Hores.setValue(0);
    }//GEN-LAST:event_butt_RestartActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Crono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butt_Restart;
    private javax.swing.JButton butt_Start;
    private javax.swing.JButton butt_Stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JProgressBar progersB_Hores;
    public static javax.swing.JProgressBar progersB_Minuts;
    public static javax.swing.JTextField textField_Hores;
    public static javax.swing.JTextField textField_Minuts;
    public static javax.swing.JTextField textField_Segons;
    // End of variables declaration//GEN-END:variables
}
